server:
  port: 9090
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
    min-response-size: 1024
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: localhost
    port: 6379
    database: 0
    password: root
    lettuce:
      pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
    timeout: 2000
  data:
      redis:
        repositories:
          enabled: false
  servlet:
      multipart:
        max-file-size: 1000MB
xc-service-manage-media:
  upload-location: /usr/local/videos
#xc-service-manage-media:
#  upload-location: F:/develop/video

mybatis:
  mapper-locations: classpath:/mappers/BookMapper.xml
  configuration:
    map-underscore-to-camel-case: true
